# netlify.toml
[build]
  command = "npm run build" # O tu comando de build, ej: "yarn build"
  publish = "dist"         # Tu carpeta de build, ej: "dist", "public"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  headers = {Content-Type = "application/xml"} # <-- Añade esta línea

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200